GCC 5 Fixes squashed gcc5: gpu: msm: fix 5.0 compile
* These need to be static to avoid these errors:

drivers/built-in.o: In function `.LANCHOR1':
msm_iommu_sec.c:(.data+0x9298): undefined reference to `kgsl_iommu_sync_lock'
msm_iommu_sec.c:(.data+0x929c): undefined reference to `kgsl_iommu_sync_unlock'
Makefile:877: recipe for target '.tmp_vmlinux1' failed
make: *** [.tmp_vmlinux1] Error 1

Signed-off-by: Chet Kener <Cl3Kener@gmail.com>

gcc5: fix warnings spam with gcc5

This fixes 102 warnings

Signed-off-by: Paul Beeler <pbeeler80@gmail.com>

gcc5: ARM: 8158/1: LLVMLinux: use static inline in ARM ftrace.h

With compilers which follow the C99 standard (like modern versions of gcc and
clang), "extern inline" does the wrong thing (emits code for an externally
linkable version of the inline function). In this case using static inline
and removing the NULL version of return_address in return_address.c does
the right thing.

Signed-off-by: Behan Webster <behanw@converseincode.com>
Reviewed-by: Mark Charlebois <charlebm@gmail.com>
Acked-by: Steven Rostedt <rostedt@goodmis.org>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>
Signed-off-by: Chet Kener <Cl3Kener@gmail.com>

gcc5: msm: camera_oppo: fix warnings with GCC 5.0

Signed-off-by: stefan <dieb.stefan.96@gmail.com>

gcc5: makefile: if -O3 disable array-bounds false positive

gcc5: sound/soc/codecs/wcd9xxx-mbhc.c fix warning: initialization discards 'const' qualifier from pointer target type

gcc5: drivers/staging/prima/CORE/MAC/src/pe/sch/schBeaconGen.c: fix warning: passing argument 2 of 'vos_mem_compare' discards 'const' qualifier from pointer target type

arm: LLVMLinux: use static inline in ARM ftrace.h

With compilers which follow the C99 standard (like modern versions of gcc and
clang), "extern inline" does the wrong thing (emits code for an externally
linkable version of the inline function). In this case using static inline
and removing the NULL version of return_address in return_address.c does
the right thing.

Signed-off-by: Behan Webster <behanw@converseincode.com>
Reviewed-by: Mark Charlebois <charlebm@gmail.com>

source: http://www.serverphorums.com/read.php?12,880351,880351#msg-880351

Conflicts:
	arch/arm/kernel/return_address.c

Change-Id: I47cde8a1f318a3d9d2e9ce6ea9a09d7250ded21e

Merged legit fixes found by arm-eabi-5.0 compiler. thanks @Alucard

https://github.com/Alucard24/Alucard-Kernel-jfltexx/commit/59c6e74d2901de9b6182fd92a2c76e10b5529411
Signed-off-by: DerRomtester <dieb.stefan.96@gmail.com>